version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./app.env
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        REACT_APP_ROLL_URL: http://host.docker.internal:8080/roll
    ports:
      - "3000:80"
    depends_on:
      - backend
